package com.zhu.prototype.entity;

import java.util.Date;

public class News {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.id
     *
     * @mbggenerated Mon Mar 02 10:02:50 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.title
     *
     * @mbggenerated Mon Mar 02 10:02:50 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.description
     *
     * @mbggenerated Mon Mar 02 10:02:50 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.picUrl
     *
     * @mbggenerated Mon Mar 02 10:02:50 CST 2015
     */
    private String picurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.src
     *
     * @mbggenerated Mon Mar 02 10:02:50 CST 2015
     */
    private String src;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.url
     *
     * @mbggenerated Mon Mar 02 10:02:50 CST 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.date
     *
     * @mbggenerated Mon Mar 02 10:02:50 CST 2015
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.content
     *
     * @mbggenerated Mon Mar 02 10:02:50 CST 2015
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.id
     *
     * @return the value of news.id
     *
     * @mbggenerated Mon Mar 02 10:02:50 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.id
     *
     * @param id the value for news.id
     *
     * @mbggenerated Mon Mar 02 10:02:50 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.title
     *
     * @return the value of news.title
     *
     * @mbggenerated Mon Mar 02 10:02:50 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.title
     *
     * @param title the value for news.title
     *
     * @mbggenerated Mon Mar 02 10:02:50 CST 2015
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.description
     *
     * @return the value of news.description
     *
     * @mbggenerated Mon Mar 02 10:02:50 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.description
     *
     * @param description the value for news.description
     *
     * @mbggenerated Mon Mar 02 10:02:50 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.picUrl
     *
     * @return the value of news.picUrl
     *
     * @mbggenerated Mon Mar 02 10:02:50 CST 2015
     */
    public String getPicurl() {
        return picurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.picUrl
     *
     * @param picurl the value for news.picUrl
     *
     * @mbggenerated Mon Mar 02 10:02:50 CST 2015
     */
    public void setPicurl(String picurl) {
        this.picurl = picurl == null ? null : picurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.src
     *
     * @return the value of news.src
     *
     * @mbggenerated Mon Mar 02 10:02:50 CST 2015
     */
    public String getSrc() {
        return src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.src
     *
     * @param src the value for news.src
     *
     * @mbggenerated Mon Mar 02 10:02:50 CST 2015
     */
    public void setSrc(String src) {
        this.src = src == null ? null : src.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.url
     *
     * @return the value of news.url
     *
     * @mbggenerated Mon Mar 02 10:02:50 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.url
     *
     * @param url the value for news.url
     *
     * @mbggenerated Mon Mar 02 10:02:50 CST 2015
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.date
     *
     * @return the value of news.date
     *
     * @mbggenerated Mon Mar 02 10:02:50 CST 2015
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.date
     *
     * @param date the value for news.date
     *
     * @mbggenerated Mon Mar 02 10:02:50 CST 2015
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.content
     *
     * @return the value of news.content
     *
     * @mbggenerated Mon Mar 02 10:02:50 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.content
     *
     * @param content the value for news.content
     *
     * @mbggenerated Mon Mar 02 10:02:50 CST 2015
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}